# config.yaml

logging:
  enabled: true        # true = logs actifs, false = logs coupés (sauf CRITICAL)
  level: INFO          # DEBUG, INFO, WARNING, ERROR, CRITICAL
  to_file: true        # true = log fichier + console, false = console seulement
  file_path: "cobol_tools.log"
  
# Répertoire où se trouvent les sources COBOL "brutes"
source_dir: "C:/Users/Utilisateur/Documents/Workplace/cobol_tools_files/cobol_source"

# Répertoire de travail
# cobol_work/
# ├── cics            ← fichiers relatifs à CICS  
# ├── csv/            ← répertoire des csv généraux
# ├── etude           ← sources normalisées (.etude)  
# ├── data/           ← dictionnaire & données (dd, usage, unused, etc.)
# │   ├── dd/
# │   ├── usage/
# │   └── unused/
# └── tmp/            ← fichiers de debug, traces, brouillons
work_dir: "C:/Users/Utilisateur/Documents/Workplace/cobol_tools_files/cobol_work"

# Répertoire de sortie pour les rapports, tableaux, graphes...
# cobol_output/
# ├── reports/        ← .md, .odt, .docx (unité : programme)
# ├── graphs/         ← .png/.svg générés à partir de .dot
# ├── consolidated/   ← CSV globaux multi-programmes
# └── log_export/     ← éventuellement, exports texte pour audit
output_dir: "C:/Users/Utilisateur/Documents/Workplace/cobol_tools_files/cobol_output"

# Type et répertoire des COPYBOOKS COBOL
copybooks:
  dir: "C:/Users/Utilisateur/Documents/Workplace/cobol_tools_files/cobol_copy"
  enabled: true

# Ficher de règles du niveau 2 d'analyse des données
data_concepts_rules_csv: "ressources/niveau_2/data_concepts_rules.csv"

# Extensions considérées comme sources COBOL
source_extensions:
  - ".cbl"
  - ".CBL"
  - ".cob"
  - ".COB"

# Numéro de départ pour la renumérotation (seq)
sequence_start: 1

# Ignorer les lignes SMASH ajoutées par le debugger
ignore_smash_lines: true


pandoc:
  exe: "C:/Program Files/Pandoc/pandoc.exe"
  lang: "fr-FR"

report:
  outputs:
    - format: "md"

    - format: "docx"
      template: null

# Suffixe pour les fichiers d'étude
etude_suffix: ".etude"

# Encodage des fichiers COBOL d'entrée
input_encoding: "latin-1"

# Encodage des fichiers produits
output_encoding: "utf-8"

# Lignes à ignorer au moment de la normalisation
ignore_prefixes:
  - "SMASH"

# Colonne commentaire COBOL (ici: '*' en col.7)
comment_column: 7

# Colonne de début du code COBOL (Area A en fixe)
code_start_column: 8

# Colonne de fin du code COBOL
code_end_column: 72

# Numéro de départ pour la renumérotation (seq)
sequence_start: 1

# Génération des images depuis .dot
generate_png_graphs: true

# Tris / filtres futurs sur les programmes
program_filters:
  # exemple : ne traiter que les programmes commençant par XXXXXXXX
  startswith:
    - "XXXXXXXX"
  
  endswith:
    - "YYYYYYYY"
